# Generated by Django 3.2.6 on 2021-08-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('discription', models.TextField(max_length=155)),
                ('category', models.CharField(max_length=20)),
                ('sub_category', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=80)),
                ('image', models.ImageField(height_field=720, upload_to='jobs/image', width_field=1080)),
            ],
        ),
    ]
