# Generated by Django 3.2.6 on 2021-08-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applyform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('birth_date', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=2)),
                ('education_completed', models.CharField(max_length=50)),
                ('pass_year', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('aadhar', models.IntegerField(max_length=16)),
                ('about', models.TextField(default='')),
                ('question', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
