# Generated by Django 3.2.6 on 2021-08-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_applyform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='aadhar',
            field=models.IntegerField(),
        ),
    ]
