# Generated by Django 3.2.6 on 2021-08-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_applyform_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyform',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/profiles/ %y / %m / % d'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(height_field=720, upload_to='jobs/image/', width_field=1080),
        ),
    ]
