# Generated by Django 3.2.6 on 2021-08-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applyform',
        ),
    ]
